/**
 * 一次性脚本：从古茗稽核 Excel dump 出所有 X.Y 格式标准条款 ID（如 H1.1、F4.1）。
 * 输出到 apps/admin/src/lib/migrations/audit-clause-ids.generated.ts，作为 v2 迁移
 * 判定「真稽核条款」的白名单常量。
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import * as XLSX from "xlsx";

const AUDIT_XLSX =
  process.env.AUDIT_XLSX ??
  "/Users/zhaobinbin/Desktop/稽核表/古茗门店稽核表20251101.xlsx";
const OUT = resolve(
  process.cwd(),
  "apps/admin/src/lib/migrations/audit-clause-ids.generated.ts",
);

interface Clause {
  id: string;
  category: string;
  score: string;
  title: string;
}

function main() {
  const wb = XLSX.readFile(AUDIT_XLSX, { cellDates: true });
  const ws = wb.Sheets[wb.SheetNames[0]];
  const aoa = XLSX.utils.sheet_to_json<unknown[]>(ws, {
    header: 1,
    defval: "",
    raw: false,
  });

  const clauses: Clause[] = [];
  for (let i = 2; i < aoa.length; i += 1) {
    const row = aoa[i] as string[];
    const id = String(row[3] ?? "").trim();
    const text = String(row[4] ?? "").trim();
    if (!id || !text) continue;
    const upper = id.toUpperCase();
    const dotCount = (id.match(/\./g) ?? []).length;
    if (dotCount !== 1) continue;
    if (!/^[A-Z]+\d+\.\d+$/.test(upper)) continue;
    clauses.push({
      id: upper,
      category: String(row[1] ?? "").trim(),
      score: String(row[2] ?? "").trim(),
      title: text,
    });
  }

  const ids = clauses.map((c) => c.id);
  const ts =
    "// AUTO-GENERATED by scripts/dump-audit-clause-ids.ts. Do not edit by hand.\n" +
    `// Source: ${AUDIT_XLSX}\n` +
    `// Generated at: ${new Date().toISOString()}\n` +
    `// Count: ${ids.length}\n\n` +
    `export const AUDIT_CLAUSE_IDS: readonly string[] = ${JSON.stringify(ids, null, 2)} as const;\n\n` +
    `export const AUDIT_CLAUSE_DETAIL: readonly { id: string; category: string; score: string; title: string }[] = ${JSON.stringify(
      clauses,
      null,
      2,
    )} as const;\n`;

  writeFileSync(OUT, ts, "utf-8");
  console.log(`[dump-audit-clause-ids] wrote ${ids.length} clause ids → ${OUT}`);
  console.log("sample:", ids.slice(0, 8).join(", "), "...");
}

main();
